# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/0983a6c0-e82b-4e5d-86db-0c846aec9a50";
  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/0983a6c0-e82b-4e5d-86db-0c846aec9a50";
      bypassWorkqueues = true;
      allowDiscards = true;
    };
  };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1cba8ab8-1e3f-48d5-84f3-fc3a0db6ee8f";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1cba8ab8-1e3f-48d5-84f3-fc3a0db6ee8f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1cba8ab8-1e3f-48d5-84f3-fc3a0db6ee8f";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/1cba8ab8-1e3f-48d5-84f3-fc3a0db6ee8f";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AC22-DCA5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
